name: "Update step"
description: "Update the course repository when the learner completes a step."
inputs:
  BRANCH_NAME:
    description: "If the learner is working in a branch, add the branch name."
    required: false
  FROM_STEP:
    description: "Requires the STEP file set to FROM_STEP."
    required: true
  GITHUB_REPOSITORY:
    description: "Set to [env.GITHUB_REPOSITORY]."
    required: true
  GITHUB_TOKEN:
    description: "Set to [secrets.GITHUB_TOKEN]."
    required: true
  TO_STEP:
    description: "The step number to go to next."
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "Check that all required env variables are set"
        if [ -z "$TO_STEP" ]
        then
          echo "TO_STEP is unset or set to the empty string"
          exit 1
        fi
        if [ -z "$FROM_STEP" ]
        then
          echo "FROM_STEP is unset or set to the empty string"
          exit 1
        fi
        if [ -z "$GITHUB_TOKEN" ]
        then
          echo "GITHUB_TOKEN is unset or set to the empty string"
          exit 1
        fi
      
        echo "Check that we are on FROM_STEP"
        if [ "$(cat .github/script/STEP)" != $FROM_STEP ]
        then
          echo "Current step is not $FROM_STEP"
          exit 0
        fi

        echo "Make sure we are on the main branch"
        git checkout main

        echo "Remove 'open' from any <details> tags"
        sed -i.tmp -r 's/<details id=([0-9]+) open>/<details id=\1>/g' README.md

        echo "Add 'open' to step TO_STEP"
        sed -i.tmp -r "s/<details id=$TO_STEP>/<details id=$TO_STEP open>/g" README.md

        echo "Update the STEP file to TO_STEP"
        echo "$TO_STEP" > .github/script/STEP

        echo "Commit the files, and push to main"
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        git add .github/script/STEP
        git commit --message="Update to $TO_STEP in STEP and README.md"
        git push

        echo "If BRANCH_NAME, update that branch as well"
        if git show-ref --quiet refs/heads/$BRANCH_NAME
        then
          git checkout $BRANCH_NAME
          git cherry-pick main
          git push
        else
          echo "Branch $BRANCH_NAME does not exist"
        fi
